services:
  web:
    image: ap1210/cloudtestia2:2.0.0
    command:
      "python /code/manage.py runserver 0.0.0.0:4502"
    volumes:
      - .:/code
    ports:
      - 4502:4502
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  postgres_data: